---
title: "PLot maps of MEMs and ESMs for the Southern Ocean"
author: "Camilla Novaglio"
date: "01/05/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Set environment 

```{r environment, echo = FALSE}

rm(list=ls())

library(raster) 
library(ggplot2) 
library(dplyr)
library(sf)
library(rnaturalearth)

select<-dplyr::select
summarise<-dplyr::summarise

my_theme_map<-theme_bw()+ 
  theme(
    text = element_text(size = 9), 
    plot.title = element_text(size = 9),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.title=element_text(size = 8), 
    legend.text=element_text(size = 7),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.background = element_blank(),
    plot.background = element_rect(fill="white"),
    panel.border = element_blank(),
    legend.key.height = unit(0.2, "cm"), # this becomes width if you choose bottom position
    legend.key.width = unit(0.5, "cm"), 
    legend.position= 'bottom' # c(0.5,0.6) # in middle
)


# load functions 
source("/home/ubuntu/Extract_SouthernOcean/R/Plotting_functions_SO.r")

```

## Load data means 

```{r}

load("/home/ubuntu/Extract_SouthernOcean/Tmp_data/01_extract_modelled_data_SO_means.RData")
ls()
mean_all

load("/home/ubuntu/Extract_SouthernOcean/Tmp_data/02_extract_input_SO_means.RData")
ls()
mean_phyto
mean_zoo

```

## Map means 

```{r}

# extract world map and prepare in circumpolar projections:  

#### Southern Ocean 
# antmap <- ne_download(scale = 110, type = 'countries') # dowloaded as spatialPoligonDataframe
# # # if you want to plot in lat/lon 
# # antmap_df <- fortify(antmap)
# pr <- "+proj=laea +lat_0=-90 +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"   
# antmap <- spTransform(antmap, CRS(pr)) 
# antmap_df <- fortify(antmap)

#### Crop region you are interested in (https://www.r-bloggers.com/2019/04/zooming-in-on-maps-with-sf-and-ggplot2/)
antmap <- ne_countries(scale = 'medium', type = 'map_units',returnclass = 'sf') # dowloaded as simple feature
antmap2 <- st_crop(antmap, xmin = -180, xmax = 180, ymin = -90, ymax = -35)
# # problem here - solved using https://github.com/r-spatial/sf/issues/1902  
# sf_use_s2(FALSE)
# antmap2 <- st_make_valid(antmap2)
# antmap2 <- st_crop(antmap2, xmin = -180, xmax = 180, ymin = -90, ymax = -50)
# ggplot() + geom_sf(data = antmap2) + theme_bw()

# from sf to spatialPoligonDataframe 
antmap <- as_Spatial(antmap2)
pr <- "+proj=laea +lat_0=-90 +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"   
antmap <- spTransform(antmap, CRS(pr)) 
antmap_df <- fortify(antmap)

# convert rasterLayer to sf object and consider circumpolar projections within function
circumpolarCRS <- CRS("+proj=laea +lat_0=-90 +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0")

###### produce maps 

## WARNING - might be better to loop to avoid mistakes ..... 
# phytoplankton  
min = 0
max = 8.75 # as per Yang et al. 2022 
legend_name = "g C m-2"

phyto_plot<-plot_SO(wmap_df = antmap_df, data_to_plot = mean_phyto, proj = circumpolarCRS, legend_name = legend_name, min = mean_phyto@data@min, max = mean_phyto@data@max)

phyto_plot<-phyto_plot+ggtitle("A) Phytoplankton")

# # check map
# phyto_plot
# plot(mean_phyto)

# mesozooplankton limits 
min = 0
max = 25 # as per Yang et al. 2022 
legend_name = "g C m-2"
  
zoo_plot<-plot_SO(wmap_df = antmap_df, data_to_plot = mean_zoo, proj = circumpolarCRS, legend_name = legend_name, min = mean_zoo@data@min, max = mean_zoo@data@max)

zoo_plot<-zoo_plot+ggtitle("B) Zooplankton")

# tcb limits size equal to all size classes 
min = 0
max = 50 
legend_name = "g C m-2"

size1_plot<-plot_SO(wmap_df = antmap_df, data_to_plot = mean_all[[1]], proj = circumpolarCRS, legend_name = legend_name, min = mean_all[[1]]@data@min, max = mean_all[[1]]@data@max)

size1_plot<-size1_plot+ggtitle("A) Total Consumers Biomass 1-10g")

size2_plot<-plot_SO(wmap_df = antmap_df, data_to_plot = mean_all[[2]], proj = circumpolarCRS, legend_name = legend_name, min = mean_all[[2]]@data@min, max = mean_all[[2]]@data@max)

size2_plot<-size2_plot+ggtitle("B) Total Consumers Biomass 10-100g")

size3_plot<-plot_SO(wmap_df = antmap_df, data_to_plot = mean_all[[3]], proj = circumpolarCRS, legend_name = legend_name, min = mean_all[[3]]@data@min, max = mean_all[[3]]@data@max)

size3_plot<-size3_plot+ggtitle("C) Total Consumers Biomass 100g-1kg")

size4_plot<-plot_SO(wmap_df = antmap_df, data_to_plot = mean_all[[4]], proj = circumpolarCRS, legend_name = legend_name, min = mean_all[[4]]@data@min, max = mean_all[[4]]@data@max)

size4_plot<-size4_plot+ggtitle("D) Total Consumers Biomass 1-10kg")

size5_plot<-plot_SO(wmap_df = antmap_df, data_to_plot = mean_all[[5]], proj = circumpolarCRS, legend_name = legend_name, min = mean_all[[5]]@data@min, max = mean_all[[5]]@data@max)

size5_plot<-size5_plot+ggtitle("E) Total Consumers Biomass 10-100kg")

size6_plot<-plot_SO(wmap_df = antmap_df, data_to_plot = mean_all[[6]], proj = circumpolarCRS, legend_name = legend_name, min = mean_all[[6]]@data@min, max = mean_all[[6]]@data@max)

size6_plot<-size6_plot+ggtitle("F) Total Consumers Biomass 100kg-1t")

```

### Save fianl plots 

```{r}

library(patchwork)

# NOT SURE WHY IT CANNOT PRINT IN RIGHT FOLDER...
# phyto and zooplankton fig 
jpeg("Fig1.jpg", width = 5, height = 5, units = "in", res = 300, bg = "transparent")
phyto_plot+zoo_plot
dev.off()

# tcb by size class 
p_final<-size1_plot+size2_plot+
  size3_plot+size4_plot+
  size5_plot+size6_plot+
  plot_layout(ncol = 3, nrow = 2)

jpeg("Fig2.jpg", width = 10, height = 10, units = "in", res = 300, bg = "transparent")
p_final
dev.off()

```


